import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import sharp from "sharp"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, "..")
const projectsDir = path.join(root, "public", "projects")
const blurOut = path.join(root, "lib", "project-banner-blurs.ts")

async function convertPngToWebp() {
  const files = fs.readdirSync(projectsDir).filter((f) => f.endsWith(".png"))
  for (const name of files) {
    const base = name.replace(/\.png$/i, "")
    const input = path.join(projectsDir, name)
    const output = path.join(projectsDir, `${base}.webp`)
    await sharp(input).webp({ quality: 82, effort: 6 }).toFile(output)
  }
}

async function writeBlurs() {
  const webps = fs
    .readdirSync(projectsDir)
    .filter((f) => f.endsWith(".webp"))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))

  const lines = [
    "/** Generated by scripts/project-banners.mjs — run after changing banner images */",
    "",
    "export const bannerBlurDataUrlByPath: Record<string, string> = {",
  ]

  for (const file of webps) {
    const bannerPath = `/projects/${file}`
    const filePath = path.join(projectsDir, file)
    const buf = await sharp(filePath)
      .resize(16, 16, { fit: "cover" })
      .jpeg({ quality: 45, mozjpeg: true })
      .toBuffer()
    const dataUrl = `data:image/jpeg;base64,${buf.toString("base64")}`
    lines.push(`  "${bannerPath}": "${dataUrl}",`)
  }

  lines.push("}", "")
  fs.writeFileSync(blurOut, lines.join("\n"))
}

async function main() {
  if (!fs.existsSync(projectsDir)) {
    throw new Error(`Missing directory: ${projectsDir}`)
  }
  await convertPngToWebp()
  await writeBlurs()
}

main().catch((err) => {
  const message = err instanceof Error ? err.stack ?? err.message : String(err)
  process.stderr.write(`${message}\n`)
  process.exit(1)
})
